### ISSUE TITLE
Problem with running docker-compose build

### ISSUE THREAD

**Issue by benmhamed-a** [ernestlwt/prototype_starter_pack#1]
Thank you for the great template. Sorry, my question might be silly because I am not very familiar with docker. I manage to adapt it to my case and when I tried to run  'docker-compose build' I get the following error:
❯ docker-compose build
WARN[0000] The "POSTGRES_USER" variable is not set. Defaulting to a blank string. 
WARN[0000] The "POSTGRES_PASSWORD" variable is not set. Defaulting to a blank string. 
WARN[0000] The "POSTGRES_USER" variable is not set. Defaulting to a blank string. 
WARN[0000] The "POSTGRES_PASSWORD" variable is not set. Defaulting to a blank string. 
WARN[0000] The "DATABASE_DIR" variable is not set. Defaulting to a blank string. 
WARN[0000] The "PGADMIN_USER" variable is not set. Defaulting to a blank string. 
WARN[0000] The "PGADMIN_PASSWORD" variable is not set. Defaulting to a blank string. 
1 error(s) decoding:

* error decoding 'Volumes[0]': invalid spec: :/var/lib/postgresql/data/pgdata: empty section between colons

Thank you for helping me with this.

**Comment by ernestlwt** [comment]
No issues with the warnings, they are only flagged because the env variable is not set and these are not needed when building.

Regarding the error, i believe newer version of docker-compose does not allow for {blank}:location as per the following line

https://github.com/ernestlwt/prototype_starter_pack/blob/d663ee6b77d97486624c9362f91f64be6c9b807a/docker-compose.yml#L45-L46

so you might need to set that env variable ${DATABASE_DIR} first. You can set it manually yourself or write something similar to the `start.sh` file before building it

take note that the js and python packages version used for this repo is pretty old too. so you might need to test and update them. Cheers

**Comment by benmhamed-a** [comment]
Thank you. I'll test what you suggested.
